import Image from "next/image";
import { Card, CardContent } from "@/components/ui/card";
import { getCollageImagesAction } from "../actions";
import Link from "next/link";
import { Button } from "@/components/ui/button";

export const dynamic = 'force-dynamic'

export default async function CollagePage() {
  const { images: collageImages, error } = await getCollageImagesAction();

  if (error) {
    return (
      <div className="container mx-auto py-8 px-4 text-center">
        <h1 className="text-2xl font-bold text-destructive">Error loading collage</h1>
        <p className="text-muted-foreground">{error}</p>
      </div>
    );
  }

  return (
    <div className="container mx-auto py-12 px-4">
      <section className="text-center mb-12">
        <h1 className="text-5xl md:text-7xl font-bold font-headline text-foreground">
          Collage of <span className="text-primary-gradient">Memories</span>
        </h1>
        <p className="mt-4 text-lg text-foreground/80 max-w-3xl mx-auto">
          A living testament to our shared creativity. Explore the artworks generated by everyone at the event.
        </p>
      </section>

      {collageImages && collageImages.length > 0 ? (
        <div className="columns-2 md:columns-3 lg:columns-4 xl:columns-5 gap-4 space-y-4">
          {collageImages.map((img) => (
            <div key={img.id} className="break-inside-avoid">
              <Card className="overflow-hidden transition-all hover:shadow-xl hover:-translate-y-1 duration-300 ease-in-out group bg-card border-border">
                <CardContent className="p-0 relative">
                  <Image
                    src={img.imageDataUri}
                    alt={`Collage image in style ${img.styleName}`}
                    width={400}
                    height={400}
                    className="w-full h-auto object-cover"
                  />
                  <div className="absolute bottom-0 left-0 right-0 bg-black/60 p-2 backdrop-blur-sm opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                    <p className="text-white text-sm font-bold text-center truncate">{img.styleName}</p>
                  </div>
                </CardContent>
              </Card>
            </div>
          ))}
        </div>
      ) : (
         <div className="text-center text-muted-foreground py-16 border-2 border-dashed border-border rounded-lg">
            <h2 className="text-2xl font-bold font-headline">The Collage is Empty</h2>
            <p className="mt-2 mb-6">Be the first to create some art to see it here!</p>
            <Button asChild className="bg-accent text-accent-foreground hover:bg-accent/90">
                <Link href="/">Create Art</Link>
            </Button>
        </div>
      )}
    </div>
  );
}
